name: create Repo
on:
  issue_comment:
    types: [ created ]
jobs:
  create-repo:
    name: create Repo
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '/create-repo')
    steps:
      - name: create Repo
        uses: Department-of-Veterans-Affairs-Sandbox/mtt-slash-cmd-create-repo@v1.0.12
        with:
          admin_token: ${{ secrets.DEVOPS_BOT_PAT }}
          repo: mtt-working-repo
